export const SOCKET_FOLDER_ADD = 'SOCKET_FOLDER_ADD';
export const SOCKET_FOLDER_EDIT = 'SOCKET_FOLDER_EDIT';
export const SOCKET_FOLDER_DELETE = 'SOCKET_FOLDER_DELETE';
export const SOCKET_FILE_ADD = 'SOCKET_FILE_ADD';
export const SOCKET_FILE_EDIT = 'SOCKET_FILE_EDIT';
export const SOCKET_FILE_DELETE = 'SOCKET_FILE_DELETE';
export const SOCKET_CODE_CHANGE = 'SOCKET_CODE_CHANGE';

export const FETCH_FOLDERS = 'FETCH_FOLDERS';
export const FOLDER_ADD = 'FOLDER_ADD';
export const FOLDER_EDIT = 'FOLDER_EDIT';
export const FOLDER_DELETE = 'FOLDER_DELETE';
export const FILE_ADD = 'FILE_ADD';
export const FILE_EDIT = 'FILE_EDIT';
export const FILE_DELETE = 'FILE_DELETE';
export const CODE_CHANGE = 'CODE_CHANGE';